It is necessary to add this flag for compilation on Windows via cl.exe, as filtered_lrelu.cpp uses "if constexpr" which is c++17, and will otherwise fail with the following error.
filtered_lrelu.cpp(147): error C4984: 'if constexpr' is a C++17 language extension